<span style="font-family:Arial; font-weight:Bold; font-size:2.3em; color:#00b3e5;"> NumPy

In [1]:
import numpy as np

# 

<span style="font-family:Arial; font-weight:Bold; font-size:1.8em; color:#00b3e5;"> Creating Arrays

<span style="font-family:Arial; font-weight:Bold; font-size:1.5em; color:#00b3e5;"> zeros

In [2]:
n=np.zeros((3,5))
n

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<span style="font-family:Arial; font-weight:Bold; font-size:1.5em; color:#00b3e5;"> full

In [3]:
n=np.full( (3,5), 7 )
n

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

<span style="font-family:Arial; font-weight:Bold; font-size:1.5em; color:#00b3e5;"> a range

In [4]:
n=np.arange(10,50,5)
n

array([10, 15, 20, 25, 30, 35, 40, 45])

<span style="font-family:Arial; font-weight:Bold; font-size:1.5em; color:#00b3e5;"> random integers

In [143]:
n=np.random.randint( 1,100, [2,5] )
n

array([[86, 25, 41, 74, 30],
       [97, 92, 44, 76, 56]])

# 

<span style="font-family:Arial; font-weight:Bold; font-size:1.8em; color:#00b3e5;"> Comparing

In [6]:
n1=np.array([10,20,30])
n2=np.array([10,30,20])

<span style="font-family:Arial; font-weight:Bold; font-size:1.5em; color:#00b3e5;"> arrays

In [8]:
np.array_equal(n1,n2)

False

<span style="font-family:Arial; font-weight:Bold; font-size:1.5em; color:#00b3e5;"> values

In [7]:
np.equal(n1,n2)

array([ True, False, False])

# 

<span style="font-family:Arial; font-weight:Bold; font-size:1.8em; color:#00b3e5;"> Stacking

In [97]:
n1=np.array([10,20])
n2=np.array([30,40])
n3=np.array([50,60])
n4=np.array([70,80])

In [98]:
np.vstack((n1,n2,n3,n4))         # np.stack((n1,n2,n3,n4), axis=0)

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [99]:
np.hstack((n1,n2,n3,n4))         # np.concatenate((n1,n2,n3,n4))

array([10, 20, 30, 40, 50, 60, 70, 80])

In [100]:
np.column_stack((n1,n2,n3,n4))   # np.stack((n1,n2,n3,n4), axis=1)

array([[10, 30, 50, 70],
       [20, 40, 60, 80]])

#####   

<span style="font-family:Arial; font-weight:Bold; font-size:1.8em; color:#00b3e5;"> concatenate == hstack

In [157]:
n1=np.array([10,20])
n2=np.array([30])
n3=np.array([40])
n4=np.array([50,60,70,80])

np.concatenate((n1,n2,n3,n4))    # np.hstack((n1,n2,n3,n4)) 

array([10, 20, 30, 40, 50, 60, 70, 80])

#####   

<span style="font-family:Arial; font-weight:Bold; font-size:1.8em; color:#00b3e5;"> Math

In [61]:
n=np.array([100,200,300])
n*3 - n/2 + 1

array([251., 501., 751.])

In [109]:
n1=np.array([ [10,15,20], 
              [25,30,35], 
              [40,45,50] 
            ])

n2=np.array(  [10,20,30]  )

n1+n2

array([[20, 35, 50],
       [35, 50, 65],
       [50, 65, 80]])

In [110]:
n1=np.array([ [ [10,20], [25,35] ],
              [ [50,60], [75,85] ], 
              [ [90,91], [95,96] ] 
            ])

n2=np.array(  [  [1,2] ,  [4,5]  ]  )

n1+n2

array([[[ 11,  22],
        [ 29,  40]],

       [[ 51,  62],
        [ 79,  90]],

       [[ 91,  93],
        [ 99, 101]]])

#####   

<span style="font-family:Arial; font-weight:Bold; font-size:1.8em; color:#00b3e5;"> Statistics

In [159]:
n=np.array([100,200,300,350,450,550,700,700])
[ np.mean(n), np.median(n), np.std(n), np.min(n), np.max(n) ]

[418.75, 400.0, 207.57152381769518, 100, 700]

#####   

<span style="font-family:Arial; font-weight:Bold; font-size:1.8em; color:#00b3e5;"> (Un)Common Elements

In [17]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])

In [18]:
np.intersect1d(n1,n2)

array([50, 60])

In [19]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [20]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

#####   

<span style="font-family:Arial; font-weight:Bold; font-size:1.8em; color:#00b3e5;"> sum

In [21]:
n1=np.array([10,20])
n2=np.array([30,40])
n3=np.array([50,60])
n4=np.array([70,80])

<span style="font-family:Arial; font-weight:Bold; font-size:1.5em; color:#00b3e5;"> all

In [25]:
np.sum([n1,n2,n3,n4])

360

<span style="font-family:Arial; font-weight:Bold; font-size:1.5em; color:#00b3e5;"> col

In [26]:
np.sum([n1,n2,n3,n4],axis=0)

array([160, 200])

<span style="font-family:Arial; font-weight:Bold; font-size:1.5em; color:#00b3e5;"> row

In [27]:
np.sum([n1,n2,n3,n4],axis=1)

array([ 30,  70, 110, 150])

#####   

<span style="font-family:Arial; font-weight:Bold; font-size:1.8em; color:#00b3e5;"> Broadcasting
    
    . 10 20
    1
    2
    3
    

In [114]:
col = np.array( [1,2,3] )
col.shape = (3,1)
col

array([[1],
       [2],
       [3]])

In [115]:
row = np.array([10,20])
row.shape = (1,2)
row

array([[10, 20]])

In [147]:
col * row

array([[10, 20],
       [20, 40],
       [30, 60]])

In [117]:
col + row

array([[11, 21],
       [12, 22],
       [13, 23]])

#####   

<span style="font-family:Arial; font-weight:Bold; font-size:1.8em; color:#00b3e5;"> Accessing Data

In [148]:
n = np.array([ [1,2,3],
               [4,5,6],
               [7,8,9]
             ])

In [124]:
n[-1]  # n[-1,:]

array([7, 8, 9])

In [119]:
n[:,-1]

array([3, 6, 9])

In [120]:
n[-1,0]

7

#####   

<span style="font-family:Arial; font-weight:Bold; font-size:1.8em; color:#00b3e5;"> Transpose

<span style="font-family:Arial; font-weight:Bold; font-size:1.5em; color:#00b3e5;"> multi-dim

In [125]:
n = np.array([ [1,2,3], 
               [4,5,6] 
             ])
n.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [152]:
n = np.array([ [1,2,3] ])
print('shape:',n.shape)
n.T

shape: (1, 3)


array([[1],
       [2],
       [3]])

<span style="font-family:Arial; font-weight:Bold; font-size:1.5em; color:#00b3e5;"> single-row
    
    - one line row arrays are hard to transpose

In [155]:
n = np.array([1, 2, 3]) 
print('shape:',n.shape)
n.T                 # KO -- it does not work

shape: (3,)


array([1, 2, 3])

In [156]:
np.array( [n] ).T   # OK -- use this

array([[1],
       [2],
       [3]])

# 

<span style="font-family:Arial; font-weight:Bold; font-size:1.8em; color:#00b3e5;"> Multiplication

<span style="font-family:Arial; font-weight:Bold; font-size:1.5em; color:#00b3e5;"> internal

In [133]:
n1 = np.array([ [1,2,3],
                [4,5,6],
              ])
n2 = np.array([ [6,5,4],
                [3,2,1],
              ])
n1*n2

array([[ 6, 10, 12],
       [12, 10,  6]])

<span style="font-family:Arial; font-weight:Bold; font-size:1.5em; color:#00b3e5;"> external

In [136]:
n1 = np.array([ [1,2],
                [3,4],
                [5,6]
              ])
n2 = np.array([ [10,9,8,7,6],
                [ 5,4,3,2,1],
              ])
n1@n2

array([[20, 17, 14, 11,  8],
       [50, 43, 36, 29, 22],
       [80, 69, 58, 47, 36]])

In [137]:
n1.dot(n2)

array([[20, 17, 14, 11,  8],
       [50, 43, 36, 29, 22],
       [80, 69, 58, 47, 36]])

#####   

<span style="font-family:Arial; font-weight:Bold; font-size:1.8em; color:#00b3e5;"> Save & Load

In [57]:
n1 = np.array([10,20,30])
np.save('my_numpy',n1)

In [58]:
n2 = np.load('my_numpy.npy')
n2

array([10, 20, 30])

#####   

#####   